# Generated by Django 3.0 on 2022-05-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('mobile', models.IntegerField(max_length=12, null=True)),
                ('emp_code', models.CharField(max_length=60, null=True)),
                ('emp_dept', models.CharField(max_length=60, null=True)),
                ('gesignation', models.CharField(max_length=60, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('join_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
