# Generated by Django 3.0 on 2022-05-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='gesignation',
            new_name='emp_desg',
        ),
    ]
