# Generated by Django 3.0 on 2022-05-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220530_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='emp_contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
