# Generated by Django 3.0 on 2022-05-30 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_employeedetails_emp_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='emp_contact',
        ),
    ]
