# Generated by Django 3.0 on 2022-05-30 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_employeedetails_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='mobile',
            new_name='emp_mobile',
        ),
    ]
