# Generated by Django 3.0 on 2022-05-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_employeeeducations_employeeexperiance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperiance',
            name='company3_desg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperiance',
            name='company3_duration',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperiance',
            name='company3_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
